# Generated by Django 6.0.1 on 2026-04-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='No Description Available.'),
        ),
        migrations.AddField(
            model_name='products',
            name='stoke',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(),
        ),
    ]
