# Generated by Django 6.0.1 on 2026-04-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_description_products_stoke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='company_name',
            field=models.CharField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='products',
            name='section',
            field=models.CharField(default='Not Available'),
        ),
    ]
