# Generated by Django 6.0.1 on 2026-04-29 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_buy_coupon_code_buy_discount_buy_final_price_and_more'),
        ('product', '0003_products_company_name_products_product_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_coupon_code', models.CharField(default='Not Available')),
                ('discount_type', models.CharField(choices=[('Fixed Amount Discounts', 'Fixed Amount Discounts'), ('Percentage Discounts (With Caps)', 'Percentage Discounts (With Caps)'), ('BOGO', 'BOGO'), ('Minimum Spend Coupons (Thresholds)', 'Minimum Spend Coupons (Thresholds)'), ('Category-Specific Discounts', 'Category-Specific Discounts'), ('First-Purchase / New User Coupons', 'First-Purchase / New User Coupons')], default='No Discount')),
                ('product', models.ForeignKey(default='Null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
