# Generated by Django 6.0.1 on 2026-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_couponcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount Discounts', 'Fixed Amount Discounts'), ('Percentage Discounts (With Caps)', 'Percentage Discounts (With Caps)'), ('BOGO', 'BOGO'), ('Minimum Spend Coupons (Thresholds)', 'Minimum Spend Coupons (Thresholds)'), ('Category-Specific Discounts', 'Category-Specific Discounts'), ('First-Purchase / New User Coupons', 'First-Purchase / New User Coupons')], default='Null'),
        ),
    ]
