# Generated by Django 6.0.1 on 2026-04-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_buy_discount_alter_buy_final_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutItem',
        ),
    ]
