# Generated by Django 6.0.1 on 2026-04-30 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_checkoutitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='buy',
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('card', 'Card'), ('upi', 'UPI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reviews',
            name='checkoutitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.checkoutitem'),
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
