# Generated by Django 6.0.1 on 2026-04-30 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_reviews_buy_checkoutitem_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='checkoutitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.checkoutitem'),
        ),
    ]
