# Generated by Django 6.0.1 on 2026-04-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_reviews_checkoutitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checkoutitem',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='checkoutitem',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('card', 'Card'), ('upi', 'UPI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
