# Generated by Django 6.0.1 on 2026-04-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_checkoutitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='checkoutitem',
        ),
        migrations.AddField(
            model_name='reviews',
            name='checkout',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='payment.checkout'),
            preserve_default=False,
        ),
    ]
