# Generated by Django 6.0.1 on 2026-04-30 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_remove_reviews_checkoutitem_reviews_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='checkout',
        ),
        migrations.AddField(
            model_name='reviews',
            name='checkoutitem',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='payment.checkoutitem'),
            preserve_default=False,
        ),
    ]
