# Generated by Django 6.0.1 on 2026-04-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_remove_reviews_checkout_reviews_checkoutitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='discount_choice',
            field=models.CharField(choices=[('all', 'Discount On Total Cart'), ('product', 'Discount On Specific Product')], default='No Discount'),
        ),
    ]
