# Generated by Django 6.0.1 on 2026-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_couponcode_discount_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='make_coupon_code',
            field=models.CharField(default='all'),
        ),
    ]
