# Generated by Django 6.0.1 on 2026-04-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_couponcode_make_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='payment_status',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('card', 'Card'), ('upi', 'UPI')], max_length=20, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.checkout')),
            ],
        ),
    ]
