# Generated by Django 6.0.1 on 2026-04-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_alter_purchase_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='checkout',
        ),
    ]
