# Generated by Django 6.0.1 on 2026-04-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_remove_purchase_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cartitem',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='payment.cartitem'),
        ),
    ]
