# Generated by Django 6.0.1 on 2026-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_purchase_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='have_address',
            field=models.BooleanField(default=False),
        ),
    ]
