# Generated by Django 6.0.1 on 2026-05-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_address_have_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='has_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
