# Generated by Django 6.0.1 on 2026-05-01 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_alter_purchase_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cartitem',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='payment.cartitem'),
        ),
    ]
