# Generated by Django 6.0.1 on 2026-05-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_alter_purchase_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
