# Generated by Django 6.0.1 on 2026-05-01 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_purchase_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='purchase',
            name='checkoutitem',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='payment.checkoutitem'),
        ),
    ]
