# Generated by Django 6.0.1 on 2026-05-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_remove_purchase_cartitem_purchase_checkoutitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='checkoutitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.checkoutitem'),
        ),
    ]
