# Generated by Django 6.0.1 on 2026-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitem',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
