# Generated by Django 6.0.1 on 2026-05-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_checkoutitem_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutitem',
            name='purchased',
        ),
    ]
