# Generated by Django 6.0.1 on 2026-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_remove_checkoutitem_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='card_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='card_holder_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='card_security_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='upi_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='upi_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
